import { Hero } from "../models/hero.model";

export const HEROES: Hero[] = [
  {id:1, name: "Homem Aranha", power: "teste"},
    {id:2, name: "Homem Gelo", power: "teste"},
    {id:3, name: "Homem Invisível", power: "teste"},
    {id:4, name: "Homem Morcego", power: "teste"},
    {id:5, name: "Homem Pedra", power: "teste"},
    {id:6, name: "Homem Fumaça", power: "teste"},
    {id:7, name: "Homem Lontra", power: "teste"},
    {id:8, name: "Homem Crocodilo", power: "teste"},
    {id:9, name: "Homem Sombra", power: "teste"},
    {id:10, name: "Homem Homem", power: "teste"},
    {id:11, name: "Homem Papagaio", power: "teste"},
    {id:12, name: "Homem Texugo", power: "teste"},
    {id:13, name: "Homem Capivara", power: "teste"},
    {id:14, name: "Homem Jumento", power: "teste"},
    {id:15, name: "Homem Carrapato", power: "teste"},
    {id:16, name: "Homem Concha", power: "teste"},
    {id:17, name: "Homem Bêbado", power: "teste"},
    {id:18, name: "Homem Mendigo", power: "teste"},
    {id:19, name: "Homem Mulher", power: "teste"},
    {id:20, name: "Homem Polenta", power: "teste"},
    {id:21, name: "Homem Carro", power: "teste"},
    {id:22, name: "Homem Biruta", power: "teste"},
    {id:23, name: "Homem Rato", power: "teste"},
    {id:24, name: "Homem Tatuado", power: "teste"},
    {id:25, name: "Homem Criança", power: "teste"},
    {id:26, name: "Homem Ladrão", power: "teste"},
    {id:27, name: "Homem Pastor", power: "teste"},
    {id:28, name: "Homem Bomba", power: "teste"},
    {id:29, name: "Homem Curvado", power: "teste"},
    {id:30, name: "Homem Profeta", power: "teste"}
];

